#!/usr/bin/python
import shutil
import os

# Load modules from $CHARM_DIR/lib
import sys
sys.path.append('lib')

from charmhelpers.core import hookenv

source = hookenv.action_get("source")
if source != "":
    shutil.rmtree(os.path.join("fetched", source))
